# This file has been generated by node2nix 1.8.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {};
  args = {
    name = "van11y-accessible-tab-panel-aria";
    packageName = "van11y-accessible-tab-panel-aria";
    version = "2.0.4";
    src = ./.;
    buildInputs = globalBuildInputs;
    meta = {
      description = "ES2015 accessible tabs panel system, using ARIA (compatible IE9+ when transpiled)";
      homepage = https://van11y.net/accessible-tab-panel/;
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}